package com.example.entity;

import com.example.entity.SequenceUserId;
import com.example.entity.SequenceUserIdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SequenceUserIdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_user_id
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int countByExample(SequenceUserIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_user_id
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int deleteByExample(SequenceUserIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_user_id
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_user_id
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int insert(SequenceUserId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_user_id
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int insertSelective(SequenceUserId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_user_id
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    List<SequenceUserId> selectByExample(SequenceUserIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_user_id
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int updateByExampleSelective(@Param("record") SequenceUserId record, @Param("example") SequenceUserIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_user_id
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int updateByExample(@Param("record") SequenceUserId record, @Param("example") SequenceUserIdExample example);
}