package com.example.entity;

import com.example.entity.TBookStatus;
import com.example.entity.TBookStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBookStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int countByExample(TBookStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int deleteByExample(TBookStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int deleteByPrimaryKey(String bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int insert(TBookStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int insertSelective(TBookStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    List<TBookStatus> selectByExample(TBookStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    TBookStatus selectByPrimaryKey(String bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int updateByExampleSelective(@Param("record") TBookStatus record, @Param("example") TBookStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int updateByExample(@Param("record") TBookStatus record, @Param("example") TBookStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int updateByPrimaryKeySelective(TBookStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int updateByPrimaryKey(TBookStatus record);
}