package com.example.entity;

import com.example.entity.TMngUserInfo;
import com.example.entity.TMngUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMngUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mng_user_info
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int countByExample(TMngUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mng_user_info
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int deleteByExample(TMngUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mng_user_info
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int deleteByPrimaryKey(String mngUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mng_user_info
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    int insert(TMngUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mng_user_info
     *
     * @mbggenerated Sat Apr 14 22:01:23 JST 2018
     */
    int insertSelective(TMngUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mng_user_info
     *
     * @mbggenerated Sat Apr 14 22:01:23 JST 2018
     */
    List<TMngUserInfo> selectByExample(TMngUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mng_user_info
     *
     * @mbggenerated Sat Apr 14 22:01:23 JST 2018
     */
    TMngUserInfo selectByPrimaryKey(String mngUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mng_user_info
     *
     * @mbggenerated Sat Apr 14 22:01:23 JST 2018
     */
    int updateByExampleSelective(@Param("record") TMngUserInfo record, @Param("example") TMngUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mng_user_info
     *
     * @mbggenerated Sat Apr 14 22:01:23 JST 2018
     */
    int updateByExample(@Param("record") TMngUserInfo record, @Param("example") TMngUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mng_user_info
     *
     * @mbggenerated Sat Apr 14 22:01:23 JST 2018
     */
    int updateByPrimaryKeySelective(TMngUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mng_user_info
     *
     * @mbggenerated Sat Apr 14 22:01:23 JST 2018
     */
    int updateByPrimaryKey(TMngUserInfo record);
}