package com.example.entity;

import java.util.Date;

public class TUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.USER_ID
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.USER_PASS
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    private String userPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.MNG_USER_ID
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    private String mngUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.USER_NAME
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.USER_ADDRESS
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.USER_SEX_KBN
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    private String userSexKbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.USER_AGE
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    private String userAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.USER_REGISTE_DATE
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    private Date userRegisteDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.USER_ID
     *
     * @return the value of t_user_info.USER_ID
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.USER_ID
     *
     * @param userId the value for t_user_info.USER_ID
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.USER_PASS
     *
     * @return the value of t_user_info.USER_PASS
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public String getUserPass() {
        return userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.USER_PASS
     *
     * @param userPass the value for t_user_info.USER_PASS
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.MNG_USER_ID
     *
     * @return the value of t_user_info.MNG_USER_ID
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public String getMngUserId() {
        return mngUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.MNG_USER_ID
     *
     * @param mngUserId the value for t_user_info.MNG_USER_ID
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public void setMngUserId(String mngUserId) {
        this.mngUserId = mngUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.USER_NAME
     *
     * @return the value of t_user_info.USER_NAME
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.USER_NAME
     *
     * @param userName the value for t_user_info.USER_NAME
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.USER_ADDRESS
     *
     * @return the value of t_user_info.USER_ADDRESS
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.USER_ADDRESS
     *
     * @param userAddress the value for t_user_info.USER_ADDRESS
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.USER_SEX_KBN
     *
     * @return the value of t_user_info.USER_SEX_KBN
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public String getUserSexKbn() {
        return userSexKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.USER_SEX_KBN
     *
     * @param userSexKbn the value for t_user_info.USER_SEX_KBN
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public void setUserSexKbn(String userSexKbn) {
        this.userSexKbn = userSexKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.USER_AGE
     *
     * @return the value of t_user_info.USER_AGE
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public String getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.USER_AGE
     *
     * @param userAge the value for t_user_info.USER_AGE
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public void setUserAge(String userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.USER_REGISTE_DATE
     *
     * @return the value of t_user_info.USER_REGISTE_DATE
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public Date getUserRegisteDate() {
        return userRegisteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.USER_REGISTE_DATE
     *
     * @param userRegisteDate the value for t_user_info.USER_REGISTE_DATE
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public void setUserRegisteDate(Date userRegisteDate) {
        this.userRegisteDate = userRegisteDate;
    }
}