package com.example.entity;

public class TUserStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_status.USER_ID
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_status.USER_HISTORY
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    private String userHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_status.USER_NUM_LENDING
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    private String userNumLending;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_status.DELAY_NUM
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    private String delayNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_status.USER_ID
     *
     * @return the value of t_user_status.USER_ID
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_status.USER_ID
     *
     * @param userId the value for t_user_status.USER_ID
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_status.USER_HISTORY
     *
     * @return the value of t_user_status.USER_HISTORY
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public String getUserHistory() {
        return userHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_status.USER_HISTORY
     *
     * @param userHistory the value for t_user_status.USER_HISTORY
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public void setUserHistory(String userHistory) {
        this.userHistory = userHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_status.USER_NUM_LENDING
     *
     * @return the value of t_user_status.USER_NUM_LENDING
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public String getUserNumLending() {
        return userNumLending;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_status.USER_NUM_LENDING
     *
     * @param userNumLending the value for t_user_status.USER_NUM_LENDING
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public void setUserNumLending(String userNumLending) {
        this.userNumLending = userNumLending;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_status.DELAY_NUM
     *
     * @return the value of t_user_status.DELAY_NUM
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public String getDelayNum() {
        return delayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_status.DELAY_NUM
     *
     * @param delayNum the value for t_user_status.DELAY_NUM
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public void setDelayNum(String delayNum) {
        this.delayNum = delayNum;
    }
}