package com.example.entity;

import java.util.ArrayList;
import java.util.List;

public class TUserStatusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public TUserStatusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserHistoryIsNull() {
            addCriterion("USER_HISTORY is null");
            return (Criteria) this;
        }

        public Criteria andUserHistoryIsNotNull() {
            addCriterion("USER_HISTORY is not null");
            return (Criteria) this;
        }

        public Criteria andUserHistoryEqualTo(String value) {
            addCriterion("USER_HISTORY =", value, "userHistory");
            return (Criteria) this;
        }

        public Criteria andUserHistoryNotEqualTo(String value) {
            addCriterion("USER_HISTORY <>", value, "userHistory");
            return (Criteria) this;
        }

        public Criteria andUserHistoryGreaterThan(String value) {
            addCriterion("USER_HISTORY >", value, "userHistory");
            return (Criteria) this;
        }

        public Criteria andUserHistoryGreaterThanOrEqualTo(String value) {
            addCriterion("USER_HISTORY >=", value, "userHistory");
            return (Criteria) this;
        }

        public Criteria andUserHistoryLessThan(String value) {
            addCriterion("USER_HISTORY <", value, "userHistory");
            return (Criteria) this;
        }

        public Criteria andUserHistoryLessThanOrEqualTo(String value) {
            addCriterion("USER_HISTORY <=", value, "userHistory");
            return (Criteria) this;
        }

        public Criteria andUserHistoryLike(String value) {
            addCriterion("USER_HISTORY like", value, "userHistory");
            return (Criteria) this;
        }

        public Criteria andUserHistoryNotLike(String value) {
            addCriterion("USER_HISTORY not like", value, "userHistory");
            return (Criteria) this;
        }

        public Criteria andUserHistoryIn(List<String> values) {
            addCriterion("USER_HISTORY in", values, "userHistory");
            return (Criteria) this;
        }

        public Criteria andUserHistoryNotIn(List<String> values) {
            addCriterion("USER_HISTORY not in", values, "userHistory");
            return (Criteria) this;
        }

        public Criteria andUserHistoryBetween(String value1, String value2) {
            addCriterion("USER_HISTORY between", value1, value2, "userHistory");
            return (Criteria) this;
        }

        public Criteria andUserHistoryNotBetween(String value1, String value2) {
            addCriterion("USER_HISTORY not between", value1, value2, "userHistory");
            return (Criteria) this;
        }

        public Criteria andUserNumLendingIsNull() {
            addCriterion("USER_NUM_LENDING is null");
            return (Criteria) this;
        }

        public Criteria andUserNumLendingIsNotNull() {
            addCriterion("USER_NUM_LENDING is not null");
            return (Criteria) this;
        }

        public Criteria andUserNumLendingEqualTo(String value) {
            addCriterion("USER_NUM_LENDING =", value, "userNumLending");
            return (Criteria) this;
        }

        public Criteria andUserNumLendingNotEqualTo(String value) {
            addCriterion("USER_NUM_LENDING <>", value, "userNumLending");
            return (Criteria) this;
        }

        public Criteria andUserNumLendingGreaterThan(String value) {
            addCriterion("USER_NUM_LENDING >", value, "userNumLending");
            return (Criteria) this;
        }

        public Criteria andUserNumLendingGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NUM_LENDING >=", value, "userNumLending");
            return (Criteria) this;
        }

        public Criteria andUserNumLendingLessThan(String value) {
            addCriterion("USER_NUM_LENDING <", value, "userNumLending");
            return (Criteria) this;
        }

        public Criteria andUserNumLendingLessThanOrEqualTo(String value) {
            addCriterion("USER_NUM_LENDING <=", value, "userNumLending");
            return (Criteria) this;
        }

        public Criteria andUserNumLendingLike(String value) {
            addCriterion("USER_NUM_LENDING like", value, "userNumLending");
            return (Criteria) this;
        }

        public Criteria andUserNumLendingNotLike(String value) {
            addCriterion("USER_NUM_LENDING not like", value, "userNumLending");
            return (Criteria) this;
        }

        public Criteria andUserNumLendingIn(List<String> values) {
            addCriterion("USER_NUM_LENDING in", values, "userNumLending");
            return (Criteria) this;
        }

        public Criteria andUserNumLendingNotIn(List<String> values) {
            addCriterion("USER_NUM_LENDING not in", values, "userNumLending");
            return (Criteria) this;
        }

        public Criteria andUserNumLendingBetween(String value1, String value2) {
            addCriterion("USER_NUM_LENDING between", value1, value2, "userNumLending");
            return (Criteria) this;
        }

        public Criteria andUserNumLendingNotBetween(String value1, String value2) {
            addCriterion("USER_NUM_LENDING not between", value1, value2, "userNumLending");
            return (Criteria) this;
        }

        public Criteria andDelayNumIsNull() {
            addCriterion("DELAY_NUM is null");
            return (Criteria) this;
        }

        public Criteria andDelayNumIsNotNull() {
            addCriterion("DELAY_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andDelayNumEqualTo(String value) {
            addCriterion("DELAY_NUM =", value, "delayNum");
            return (Criteria) this;
        }

        public Criteria andDelayNumNotEqualTo(String value) {
            addCriterion("DELAY_NUM <>", value, "delayNum");
            return (Criteria) this;
        }

        public Criteria andDelayNumGreaterThan(String value) {
            addCriterion("DELAY_NUM >", value, "delayNum");
            return (Criteria) this;
        }

        public Criteria andDelayNumGreaterThanOrEqualTo(String value) {
            addCriterion("DELAY_NUM >=", value, "delayNum");
            return (Criteria) this;
        }

        public Criteria andDelayNumLessThan(String value) {
            addCriterion("DELAY_NUM <", value, "delayNum");
            return (Criteria) this;
        }

        public Criteria andDelayNumLessThanOrEqualTo(String value) {
            addCriterion("DELAY_NUM <=", value, "delayNum");
            return (Criteria) this;
        }

        public Criteria andDelayNumLike(String value) {
            addCriterion("DELAY_NUM like", value, "delayNum");
            return (Criteria) this;
        }

        public Criteria andDelayNumNotLike(String value) {
            addCriterion("DELAY_NUM not like", value, "delayNum");
            return (Criteria) this;
        }

        public Criteria andDelayNumIn(List<String> values) {
            addCriterion("DELAY_NUM in", values, "delayNum");
            return (Criteria) this;
        }

        public Criteria andDelayNumNotIn(List<String> values) {
            addCriterion("DELAY_NUM not in", values, "delayNum");
            return (Criteria) this;
        }

        public Criteria andDelayNumBetween(String value1, String value2) {
            addCriterion("DELAY_NUM between", value1, value2, "delayNum");
            return (Criteria) this;
        }

        public Criteria andDelayNumNotBetween(String value1, String value2) {
            addCriterion("DELAY_NUM not between", value1, value2, "delayNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_status
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 14 22:01:22 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_status
     *
     * @mbggenerated Sat Apr 14 22:01:22 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}